### ISSUE TITLE
Team formation

### ISSUE THREAD

**Issue by raelga** [kcdspain/spain-2023#1]
## What

We'll need to fill the following core roles + shadows to get the ball rolling. The current list of role responsibilities is just a suggestion based on the last KCD Spain 2022. 

Each team will decide on sub-team roles and responsibilities (ie - marketing lead will determine if a writer is needed) based on the direction of the event.

**Shadows** for the roles do not need to have event experience but should be ok with taking a **Lead** role within the next 12 months of events.

## How

The Guide from the Kubernetes Community Days website:

https://kubernetescommunitydays.org/organizing/

The checklist:

[Kubernetes Community Days Conference Action Items and Assignments](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=0)

#### Responsibilities

- Project management
- CNCF interactions
- SIG-Contribex interactions
- Sponsorship (if applies)

##### Time required

~3-4 hours each week, with some extra work during the early stages.

#### Responsibilities

- Define event tracks and schedule
- Talk introduction / moderation
- Call for proposals ingestion / Speakers

##### Time required

~4 hours each week, mid term to handle the call for papers evaluations and the schedule / tracks creation.

#### Responsibilities

- Website
- Social media / Community management
- Call for proposals form
- Swag (if applies)

##### Time required

~6 hours each week, pretty consisten work: early stages to start talking about the event, mid term to raise awareness for the call for papers, near the event date to publicity the event and the talks, during the event to create momentun in the social networks.

#### Responsibilities

- Bevy platform setup
- Streaming production
- Recordings edit / publication
- Technical support

##### Time required

~4 hours each week, mostly when the event date approaches. The week of the event, it almost require full time dedication.

## Team

Teams and roles will be decided during the early days of planning after summer, as we still don't the kind of event that will end occurring.

## Team

Teams and roles will be decided during the early days of planning after summer, as we still don't the kind of event that will end occurring.

| Role               | Lead | Shadow | Notes |
| ------------------ | ---- | ------ | ----- |
| Event coordination |  @raelga     |   @immavalls <br> @antonioberben  <br> @lamadome   |       |
| Content            |  @JorTurFer  | @vjjmiras <br> @mvazquezc <br>  @dcristobalhMad <br>  @Paken <br> @lamadome   |       |
| Marketing          | @vjjmiras     |  @raelga <br> @immavalls <br> @antonioberben <br>  @carvido1  <br> @birthmarkbart      |       |
| Multimedia         |      |   @carvido1      |       |

**Comment by mvazquezc** [comment]
Count me in for content!  if nobody wants to lead I can be lead, otherwise, I'll shadow.

**Comment by raelga** [comment]
Me apunto en el role de Event Lead.

**Comment by immavalls** [comment]
Me apunto a shadow en event coordination y marketing, siendo nueva.

**Comment by antonioberben** [comment]
Te copio imma: Me apunto a coordination y marketing, shadowing 💪

**Comment by Paken** [comment]
Me puedes poner como shadow en content

**Comment by carvido1** [comment]
Buenas, me apunto como shadow en multimedia

**Comment by vjjmiras** [comment]
Me apunto como lead en marketing y shadow en content.

**Comment by raelga** [comment]
@kcdspain/spain-2023 ✨

**Comment by lamadome** [comment]
m apunto para event coordination and content en shadow

**Comment by vthot4** [comment]
Me puedes apuntar como content shadow

**Comment by immavalls** [comment]
Closing this issue as KCD Spain 2023 is done
