### ISSUE TITLE
¡Participa!

### ISSUE THREAD

**Issue by raelga** [kcdspain/spain-2023#2]
Si te gustaría participar en el próximo KCD Spain 2023 pero no sabes por dónde empezar, deja un comentario en este issue y nos pondremos en contacto cuando empiece la planificación del evento.

**Comment by Paken** [comment]
Hola, aunque actualmente no vivo en España, me gustaría participar en la organización del próximo KCD en España. Si es necesario puedo desplazarme para un par de reuniones en España; y por supuesto en las fechas del KCD.

**Comment by ramrodo** [comment]
A mí también me gustaría ayudar en la organización del KCD Spain, Rael. Estaré atento a cualquier aviso para empezar.

**Comment by alonsomoya** [comment]
Hola 👋. Estaría interesado en colaborar, aunque también vivo en el extranjero (Alemania) y sólo me podría desplazar físicamente de forma ocasional

**Comment by Paken** [comment]
Una pregunta: ¿No tendría más sentido abrir un issue en https://github.com/cncf/kubernetes-community-days donde las demás comunidades lo están haciendo? Ahí tendríamos más visibilidad.

También podríamos pedir ayuda a https://twitter.com/birthmarkbart?s=21&t=DozjuqtXyOp3Boyb6nI6OQ. Hace unos días estuve hablando con él para grabar parte del anuncio para el KCD Guatemala donde yo  participo con una charla. Bart es un americano que vive desde hace unos años en Bilbao; él es muy activo dentro de las comunidades relacionadas con CNCF y Kubernetes.

**Comment by dcristobalhMad** [comment]
Buenas, a mi también me gustaría echar una mano 😊

**Comment by immavalls** [comment]
Me encantaria echar una mano tambien!

**Comment by raelga** [comment]
> Una pregunta: ¿No tendría más sentido abrir un issue en https://github.com/cncf/kubernetes-community-days donde las demás comunidades lo están haciendo? Ahí tendríamos más visibilidad.

Buenas,

Primero hay que formar un equipo y luego definir los roles en https://github.com/kcdspain/spain-2023/issues/1. Una vez definidos, se abre el issue en el repositorio que indicas.

Un saludo,

**Comment by Paken** [comment]
Ok, perfecto. Podemos empezar con una videoconferencia con los que estamos aquí para conocernos y formar el equipo. Aunque imagino que hay gente de otros años que no está en esta conversación. Ya nos dices. Un saludo.

**Comment by mvazquezc** [comment]
Yo también estoy dispuesto a colaborar!

**Comment by lamadome** [comment]
Hola! Contar conmigo para colaborar!

**Comment by eddymdz** [comment]
Hola! yo también quisiera participar

**Comment by carvido1** [comment]
Buenas! Me gustaría formar parte también del evento :) un saludo

**Comment by raelga** [comment]
Buenas a todos y todas!

Se está arrancando la organización del KCD Spain para finales de año. El próximo martes tenemos la primera reunión.

Más información en el [Slack de la CNCF](https://cloud-native.slack.com/archives/C01QU0FHEEA/p1695980986232849?thread_ts=1695380871.640889&channel=C01QU0FHEEA&message_ts=1695980986.232849).

**Comment by raelga** [comment]
Equipos formados en https://github.com/kcdspain/spain-2023/issues/1
